### ISSUE TITLE
求助接受消息api地址

### ISSUE THREAD

**Issue by willnight01** [getway/qyweixin#1]
在申请企业微信api token和encodingaeskey的时候需要url回调测试，请问这块任何配置，求解释。

**Comment by getway** [comment]
登录企业微信官网，点开 [应用与小程序]， 创建自己的应用，点开应用，设置 [接收消息]下的 [设置API接收]， URL就是本程序公网的地址，Token和EncodingAESKey 随机生成后，配置在config.py中启动即可

**Comment by willnight01** [comment]
您好，
我按照您的指导完成了配置后报错404，还是无法通过校验。
我url填写的是程序的公网地址如下， http://xxx.xxx.xxx.xxx:5001
还是报错回调url校验失败，程序中的错误log如下：
 [05/May/2019 23:03:16] "GET /?msg_signature=6dccd24cc34eab2f064dc8bbef63e3fa78921aa8&timestamp=1557068604&nonce=1556858105&echostr=Wd0lRbavr3NG7WHgnYYM6R8teGgqEFJc18O7v%2BYeohxftjZRZXbGHe%2FkMzwKW7%2FgSTj05cePFAKebhIdyeCRvA%3D%3D HTTP/1.1" 404 -
请指教。

**Comment by getway** [comment]
http://ip:端口/wechat

**Comment by willnight01** [comment]
非常感谢，我已经完成了api接口的联通，对于图灵的日常问题调用也已经可以使用了，
但是   我尝试了 !问题  去查询zabbix 
查询的时候出现了以下报错。
劳烦您解答，非常感谢。

[2019-05-06 09:35:59,339] ERROR in app: Exception on /wechat [POST]
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/python3/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/python3/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/python3/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/python3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/python3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "main.py", line 94, in wechat
    zabbix = ZabbixGraph()
  File "/data/deploy/qyweixin/zabbix.py", line 44, in __init__
    self.token = self.get_token()
  File "/data/deploy/qyweixin/zabbix.py", line 130, in get_token
    res_data = json.loads(res.content)
  File "/usr/local/python3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
10.240.2.14 - - [06/May/2019 09:35:59] "POST /wechat?msg_signature=a5dcf0993042890dbe53628de03b0e2daa7a0b0f&timestamp=1557106568&nonce=1557018745 HTTP/1.1" 500 -
[2019-05-06 09:35:59,432] ERROR in app: Exception on /wechat [POST]
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/python3/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/python3/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/python3/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/python3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/python3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "main.py", line 94, in wechat
    zabbix = ZabbixGraph()
  File "/data/deploy/qyweixin/zabbix.py", line 44, in __init__
    self.token = self.get_token()
  File "/data/deploy/qyweixin/zabbix.py", line 130, in get_token
    res_data = json.loads(res.content)
  File "/usr/local/python3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
10.240.2.14 - - [06/May/2019 09:35:59] "POST /wechat?msg_signature=a5dcf0993042890dbe53628de03b0e2daa7a0b0f&timestamp=1557106568&nonce=1557018745 HTTP/1.1" 500 -
[2019-05-06 09:35:59,523] ERROR in app: Exception on /wechat [POST]
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/python3/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/python3/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/python3/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/python3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/python3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "main.py", line 94, in wechat
    zabbix = ZabbixGraph()
  File "/data/deploy/qyweixin/zabbix.py", line 44, in __init__
    self.token = self.get_token()
  File "/data/deploy/qyweixin/zabbix.py", line 130, in get_token
    res_data = json.loads(res.content)
  File "/usr/local/python3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
10.240.2.14 - - [06/May/2019 09:35:59] "POST /wechat?msg_signature=a5dcf0993042890dbe53628de03b0e2daa7a0b0f&timestamp=1557106568&nonce=1557018745 HTTP/1.1" 500 -

**Comment by getway** [comment]
检查下config.py里面的zabbix的url，用户名和密码是否正确
